#!/usr/bin/env python


if __name__ == "__main__":
    from dfa import DFA
    import sys
    
    if len(sys.argv) > 1:
        m = DFA()
        try:
            m.load_from_yaml(sys.argv[1])
        except Exception, e:
            print e
            print "Can't load automaton."
            exit(-1)

        while True:
            try:
                print "String: ", 
                m.accepts(raw_input())
            except KeyboardInterrupt:
                exit(0)
            except Exception, e:
                print e
                print "String is not valid."
    else:
        print "Give me an automaton."
